### ISSUE TITLE
13. Utilizing secondary connections. Brad?

### ISSUE THREAD

**Issue by bradatefi** [bradatefi/mybuddies#14]
We have this data, I think it would be good to show secondary connections for jobs as well so you can see friends of friends.  With that being said, our simple approach keeps the network at a higher quality and higher level of reliability

**Comment by bradatefi** [comment]
@bahmanatefi @dminassi Can you two discuss and decide if you feel this is important enough to push higher up our list of priorities

**Comment by bahmanatefi** [comment]
I would like to discuss this for a few minutes and better understand what we have to do to accomplish this.
