### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by dminassi** [bradatefi/mybuddies#16]
Report 1:
Number of Referrals                       # of Employees                 as of Date

If I click on number, It will display
Name of Referred                            By Whom                            Date of Referral                          Date Hired       

Report 2:
# of referred Employees signed up                          As of Dates

 If I click on number it will display:
 Referred Employee Name                            Referred Employee Email     As of Date

Report 3:
# of Position                       # of likes

 If I click on number it will display:
Position Name                  Referred Employee Name                            Referred Employee Email

**Comment by bradatefi** [comment]
@dminassi I think it would be most efficient if we combined all the reports in to one document and removed the reports in the 'issues' section.  May you take the lead on this Dro?  Once you have copied the information you need you can close each of the issues.

**Comment by bradatefi** [comment]
report 3 is already in place.  reports 1 and 2 are being worked on and are first on the list after notifications is 100% complete
