### ISSUE TITLE
2. Price of service after 12 months.  Our current suggestion is 1% of employee's salary hired through our site but we would listen to other suggestions.

### ISSUE THREAD

**Issue by bradatefi** [bradatefi/mybuddies#2]
I think that is correct, lets see what they say.

**Comment by bradatefi** [comment]
I think we are agreed that we are going to stick with this but be open to what the company suggests as well and work with them to come to an amicable agreement.  If this is so, please comment and we can close this issue.

**Comment by bradatefi** [comment]
@bahmanatefi @dminassi please comment if you are ok with this and I can close the issue

**Comment by bahmanatefi** [comment]
I agree.

**Comment by bahmanatefi** [comment]
@bradatefi @dminassi     I agree.
