### ISSUE TITLE
Overall goals and objectives

### ISSUE THREAD

**Issue by bradatefi** [bradatefi/mybuddies#5]

**Comment by bradatefi** [comment]
Bahman, do you want to take the initiative on creating the initial concepts for a 'Goals and objectives' deck?

**Comment by bradatefi** [comment]
@bahmanatefi however you want to present this go ahead and start working on it and we can have somebody come in and design it and perfect the language once a draft is complete.

**Comment by bahmanatefi** [comment]
I will work with Dro on this. So this issue remains open. My initial thought as goals are to assess:
a.  what percentage of new hires give how many referrals
b. what percentage of all employees sign up and give how many referrals
c. ultimate test of what percentage of new hires are hired through our referral process
