### ISSUE TITLE
Goals for Dovel

### ISSUE THREAD

**Issue by bradatefi** [bradatefi/mybuddies#6]

**Comment by bradatefi** [comment]
How shall we do this.  Do we want to create a document that clearly states what results we are hoping to get from the engagement?  Who wants to take the lead on this?

**Comment by bradatefi** [comment]
@dminassi @bahmanatefi Can you collaborate on putting a document together outlining the goals for this?

**Comment by bahmanatefi** [comment]
I will work with Dro on this. But ultimately the best test is to know what percentage of employees currently come from normal referrals and how our system enhance this process. For a larger company I would also want to measure the cost savings. So if a company currently spends $500 K on Monster, etc. and gets only 10-15% from referrals, can we enhance this to 40-50% and in that process lower the subscription cost by $100-150 K.
